#################################
# Dependabot Configuration File #
#################################

# This is the current version of the GitHub-native Dependabot
version: 2

updates:
  # Enable version updates for npm
  - package-ecosystem: 'npm'
    # Look for `package.json` and `lock` files in the `root` directory
    directory: '/'
    # Check for updates once a week
    schedule:
      interval: 'weekly'

  # Enable version updates for Docker
  - package-ecosystem: 'docker'
    # Look for a `Dockerfile` in the `/docker/puppeteer` directory
    directory: '/docker/puppeteer'
    # Check for updates once a week
    schedule:
      interval: 'weekly'

  # Enable version updates for Docker
  - package-ecosystem: 'docker'
    # Look for a `Dockerfile` in the `/docker/fonts` directory
    directory: '/docker/fonts'
    # Check for updates once a week
    schedule:
      interval: 'weekly'
