name: CD for fonts package

on:
  release:
    types:
      - published

env:
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true

jobs:
  deploy_npm:
    defaults:
      run:
        working-directory: "packages/fonts"
    name: Deploy to npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: npm install --no-audit

      - name: Publish package
        run: bash deploy.sh
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
          repository: creativecommons/vocabulary
          event-type: fonts-built
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
