name: "Project Automation"
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
jobs:
  join_issue_pr_to_project:
    runs-on: ubuntu-latest
    steps:
    - name: "Automate adding issues"
      uses: docker://takanabe/github-actions-automate-projects:v0.0.1
      if: github.event_name == 'issues'
      env:
        GITHUB_TOKEN: ${{ secrets.ORG_GITHUB_TOKEN }}
        GITHUB_PROJECT_URL: https://github.com/orgs/creativecommons/projects/13
        GITHUB_PROJECT_COLUMN_NAME: "To Triage"
    - name: "Automate adding PRs"
      uses: docker://takanabe/github-actions-automate-projects:v0.0.1
      if: github.event_name == 'pull_request'
      continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.ORG_GITHUB_TOKEN }}
        GITHUB_PROJECT_URL: https://github.com/orgs/creativecommons/projects/13
        GITHUB_PROJECT_COLUMN_NAME: "In Progress"
